'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Mensagens
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Cappta.Gp.Api.Com.Sample.VB.Mensagens", GetType(Mensagens).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Não autorizado. Por favor, realize a autenticação para utilizar o CapptaGpPlus.
        '''</summary>
        Friend Shared ReadOnly Property RESULTADO_CAPPTA_1() As String
            Get
                Return ResourceManager.GetString("RESULTADO_CAPPTA_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Uma reimpressão ou cancelamento foi executada dentro de uma sessão multi-cartões.
        '''</summary>
        Friend Shared ReadOnly Property RESULTADO_CAPPTA_10() As String
            Get
                Return ResourceManager.GetString("RESULTADO_CAPPTA_10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to O CapptaGpPlus esta sendo inicializado, tente novamente em alguns instantes.
        '''</summary>
        Friend Shared ReadOnly Property RESULTADO_CAPPTA_2() As String
            Get
                Return ResourceManager.GetString("RESULTADO_CAPPTA_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to O formato da requisição recebida pelo CapptaGpPlus é inválido.
        '''</summary>
        Friend Shared ReadOnly Property RESULTADO_CAPPTA_3() As String
            Get
                Return ResourceManager.GetString("RESULTADO_CAPPTA_3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Operação cancelada pelo operador.
        '''</summary>
        Friend Shared ReadOnly Property RESULTADO_CAPPTA_4() As String
            Get
                Return ResourceManager.GetString("RESULTADO_CAPPTA_4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pagamento não autorizado/pendente/não encontrado.
        '''</summary>
        Friend Shared ReadOnly Property RESULTADO_CAPPTA_5() As String
            Get
                Return ResourceManager.GetString("RESULTADO_CAPPTA_5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pagamento ou cancelamento negados pela rede adquirente.
        '''</summary>
        Friend Shared ReadOnly Property RESULTADO_CAPPTA_6() As String
            Get
                Return ResourceManager.GetString("RESULTADO_CAPPTA_6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ocorreu um erro interno no CapptaGpPlus.
        '''</summary>
        Friend Shared ReadOnly Property RESULTADO_CAPPTA_7() As String
            Get
                Return ResourceManager.GetString("RESULTADO_CAPPTA_7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ocorreu um erro na comunicação entre a CappAPI e o CapptaGpPlus.
        '''</summary>
        Friend Shared ReadOnly Property RESULTADO_CAPPTA_8() As String
            Get
                Return ResourceManager.GetString("RESULTADO_CAPPTA_8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Não é possível realizar uma operação sem que se tenha finalizado o último pagamento.
        '''</summary>
        Friend Shared ReadOnly Property RESULTADO_CAPPTA_9() As String
            Get
                Return ResourceManager.GetString("RESULTADO_CAPPTA_9", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
